version: '3.8'


services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  parser:
    image: parser
    container_name: parser
    build:
      context: .
    ports:
      - 8080
    depends_on:
      - postgres

